/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("com.intuit.karate:karate-apache:0.9.6")
    testImplementation("com.intuit.karate:karate-junit5:0.9.6")
}

group = "com.softwarethatmatters.karate.maven"
version = "1.0-SNAPSHOT"
description = "karate-gradle-kotlin-setup"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

sourceSets {
    test {
        resources {
            srcDirs("src/test/resources","src/test/java")
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

tasks.register<JavaExec>("karateExecute") {
    classpath = sourceSets.test.get().runtimeClasspath
    main = System.getProperty("mainClass")
}